### ISSUE TITLE
Did not disappear if connected

### ISSUE THREAD

**Issue by phiomet** [StudiosZ/SaltyNui#1]
The overlay does not disappear when you are connected to the Teamspeak server.
Error: Uncaught TypeError: Cannot read property 'style' of null (@saltynui/html/script.js:19)

**Comment by phiomet** [comment]
Found solution. In the script.js the reference has to be pluginScreenWindow instead of pluginScreen on line 19.

**Comment by StudiosZ** [comment]
The Bug is fixed. Thanks for the information.
